//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 12:38:58 PM CEST 
//


package de.l3s.flower.jaxb;


import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}conectingtopic" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="cat1" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="cat2" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="similarity" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Connection {

    @XmlElement(required = true)
    protected List<TopicLink> conectingtopic;
    @XmlAttribute(name = "cat1", required = true)
    protected Integer cat1;
    @XmlAttribute(name = "cat2", required = true)
    protected Integer cat2;
    @XmlAttribute(name = "similarity", required = true)
    protected Double similarity;

    /**
     * Gets the value of the conectingtopic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conectingtopic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTopic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Topic }
     * 
     * 
     */
    public List<TopicLink> getTopic() {
        if (conectingtopic == null) {
            conectingtopic = new ArrayList<TopicLink>();
        }
        return this.conectingtopic;
    }

    /**
     * Gets the value of the cat1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCat1() {
        return cat1;
    }

    /**
     * Sets the value of the cat1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCat1(Integer value) {
        this.cat1 = value;
    }

    /**
     * Gets the value of the cat2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCat2() {
        return cat2;
    }

    /**
     * Sets the value of the cat2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCat2(Integer value) {
        this.cat2 = value;
    }

    /**
     * Gets the value of the similarity property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSimilarity() {
        return similarity;
    }

    /**
     * Sets the value of the similarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSimilarity(Double value) {
        this.similarity = value;
    }
public Connection() {
	this.conectingtopic=new ArrayList<TopicLink>();
}
public void addConnectingtopic(TopicLink t)
{
	conectingtopic.add(t);
}

{
	
}


}
